Fix up style/formatting

diff --git a/.github/workflows/appsignals-e2e-ec2-test.yml b/.github/workflows/appsignals-e2e-ec2-test.yml
--- a/.github/workflows/appsignals-e2e-ec2-test.yml
+++ b/.github/workflows/appsignals-e2e-ec2-test.yml
@@ -1,7 +1,11 @@
 # This is a reusable workflow for running the E2E test for App Signals.
 # It is meant to be called from another workflow.
+# This E2E test is responsible for validating setting up a sample application on an EC2 instance and enabling
+# App Signals using the staging .rpm of Cloudwatch Agent. It validates the generated telemetry
+# including logs, metrics, and traces, then cleans up the cluster. The testing resources can be found in the
+# ADOT java instrumentation repo: https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/testing
 # Read more about reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
-name: App Signals Enablement E2E Testing - EC2 Use Case
+name: App Signals Enablement E2E Testing - EC2
 on:
   workflow_call:
 
@@ -60,6 +64,13 @@ jobs:
           old_command='"wget -O cw-agent.rpm ${var.cw_agent_rpm}",'
           new_command='"aws s3 cp ${{ env.APP_SIGNALS_CW_AGENT_RPM }} ./cw-agent.rpm",'
           sed -i "s|$old_command|$new_command|" "main.tf"
+          
+          if grep -Fq '"aws s3 cp ${{ env.APP_SIGNALS_CW_AGENT_RPM }} ./cw-agent.rpm",' main.tf; then
+            echo "Command replaced successfully"
+          else
+            echo "sed command failed, exiting."
+            exit 1
+          fi
 
       - name: Set up terraform
         uses: hashicorp/setup-terraform@v3
@@ -80,15 +91,16 @@ jobs:
             -var="adot_jar=${{ env.APP_SIGNALS_ADOT_JAR }}"
 
       - name: Get the ec2 instance ami id
+        working-directory: testing/terraform/ec2
         run: |
           echo "EC2_INSTANCE_AMI=$(terraform output ec2_instance_ami)" >> $GITHUB_ENV
-        working-directory: testing/terraform/ec2
 
       - name: Get the sample app endpoint
+        working-directory: testing/terraform/ec2
         run: |
           echo "MAIN_SERVICE_ENDPOINT=$(terraform output sample_app_main_service_public_dns):8080" >> $GITHUB_ENV
           echo "REMOTE_SERVICE_IP=$(terraform output sample_app_remote_service_public_ip)" >> $GITHUB_ENV
-        working-directory: testing/terraform/ec2
+      
         
       - name: Wait for app endpoint to come online
         id: endpoint-check
