add ssm doc/param clean up

diff --git a/.github/workflows/clean-aws-resources.yml b/.github/workflows/clean-aws-resources.yml
--- a/.github/workflows/clean-aws-resources.yml
+++ b/.github/workflows/clean-aws-resources.yml
@@ -309,3 +309,40 @@ jobs:
           set -e
           go run ./clean_security_group/clean_security_group.go || { echo "Failed to clean security groups"; exit 1; }
 
+  clean-ssm-documents:
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write
+      contents: read
+    strategy:
+      matrix:
+        region: [
+          us-east-1, us-east-2,
+          us-west-1, us-west-2,
+          ap-southeast-1, ap-southeast-2,
+          ap-south-1,
+          ap-northeast-1, ap-northeast-2, ap-northeast-3,
+          ca-central-1,
+          eu-central-1,
+          eu-west-1, eu-west-2, eu-west-3,
+          eu-north-1,
+          sa-east-1
+        ]
+      fail-fast: false
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}
+          aws-region: ${{ matrix.region }}
+
+      - name: Clean Old Test SSM Documents and Parameters
+        working-directory: tool/clean
+        run: |
+          set -e
+          echo "Cleaning test SSM documents and parameters in ${{ matrix.region }}"
+          go run ./clean_ssm_documents/clean_ssm_documents.go --dry-run=false || { echo "Failed to clean SSM documents in ${{ matrix.region }}"; exit 1; }
+
