updated yml

diff --git a/.github/workflows/goCache.yml b/.github/workflows/goCache.yml
--- a/.github/workflows/goCache.yml
+++ b/.github/workflows/goCache.yml
@@ -45,29 +45,36 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
-
       - name: go mod optimization
         run: |
           if aws s3 ls "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"; then
             aws s3 cp "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip" ./vendor.zip
             time unzip vendor.zip
             rm -r vendor.zip
-            set +e
-            (go build -mod=vendor .)
-            build_exit_status=$?
-            if [ $build_exit_status -ne 0 ]; then   #if package is updated we are able to handle with is this functionality.
-              echo "Error detected while running 'go build -mod=vendor .'"
-              go mod tidy
-              go mod vendor
-              zip -r vendor.zip vendor
-              aws s3 cp vendor.zip "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"
-              rm -f vendor.zip
-            else
-              echo "Build successful"
-            fi
-          else
-            time go mod vendor
-            zip -r vendor.zip vendor
-            aws s3 cp vendor.zip "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"
-          fi
-          set -e
+            wget https://amazoncloudwatch-agent.s3.amazonaws.com/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
+            sudo rpm -Uvh amazon-cloudwatch-agent.rpm
+#      - name: go mod optimization
+#        run: |
+#          if aws s3 ls "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"; then
+#            aws s3 cp "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip" ./vendor.zip
+#            time unzip vendor.zip
+#            rm -r vendor.zip
+#            set +e
+#            (go build -mod=vendor .)
+#            build_exit_status=$?
+#            if [ $build_exit_status -ne 0 ]; then   #if package is updated we are able to handle with is this functionality.
+#              echo "Error detected while running 'go build -mod=vendor .'"
+#              go mod tidy
+#              go mod vendor
+#              zip -r vendor.zip vendor
+#              aws s3 cp vendor.zip "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"
+#              rm -f vendor.zip
+#            else
+#              echo "Build successful"
+#            fi
+#          else
+#            time go mod vendor
+#            zip -r vendor.zip vendor
+#            aws s3 cp vendor.zip "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"
+#          fi
+#          set -e
