adding test

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -1199,7 +1199,7 @@ jobs:
             else
               cd terraform/eks/addon/gpu
             fi
-
+            
             terraform init
             if terraform apply --auto-approve \
               -var="aws_ecr_private_registry=${{ secrets.AWS_ECR_PRIVATE_REGISTRY }}" \
@@ -1217,6 +1217,28 @@ jobs:
               terraform destroy -auto-approve && exit 1
             fi
 
+      - name: Apply GPU burner YAML
+        run: kubectl apply -f ./gpuBurner.yaml
+
+      - name: Create NVIDIA device plugin
+        run: kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.15.0/deployments/static/nvidia-device-plugin.yml
+
+      - name: Patch the CloudWatch Agent image and restart CloudWatch pods
+        run: |
+          kubectl patch amazoncloudwatchagents -n amazon-cloudwatch cloudwatch-agent --type='json' -p='[{"op": "replace", "path": "/spec/image", "value": ${{ secrets.AWS_ECR_PRIVATE_REGISTRY }}/${{ env.ECR_INTEGRATION_TEST_REPO }}:${{ github.sha }}}]'
+          kubectl delete pods --all -n amazon-cloudwatch
+          sleep 10
+          kubectl wait --for=condition=Ready pod --all -n amazon-cloudwatch
+
+      - name: Run tests
+        run: |
+          if go test ${var.test_dir} -eksClusterName ${aws_eks_cluster.this.name} -computeType=EKS -v -eksDeploymentStrategy=DAEMON -eksGpuType=nvidia; then
+            echo "Tests passed"
+          else
+            echo "Tests failed"
+            exit 1
+          fi
+
       - name: Terraform destroy
         if: ${{ cancelled() || failure() }}
         uses: nick-fields/retry@v2
@@ -1226,6 +1248,9 @@ jobs:
           retry_wait_seconds: 5
           command: cd terraform/eks/addon/gpu && terraform destroy --auto-approve
 
+      - name: Final Terraform destroy
+        if: ${{ always() }}
+        run: cd terraform/eks/addon/gpu && terraform destroy --auto-approve
 
   StressTrackingTest:
     name: "StressTrackingTest"
