adding gpu metrics

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -858,6 +858,85 @@ jobs:
               cd terraform/ecs_fargate/linux
             fi
             terraform destroy --auto-approve
+  GPUE2E:
+    name: "GPUE2E"
+    needs: [ BuildAndUpload, BuildAndUploadPackages, GenerateTestMatrix ]
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        arrays: ${{ fromJson(needs.GenerateTestMatrix.outputs.eks_addon_matrix) }}
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
+          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+          aws-region: us-west-2
+          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }}
+
+
+      - name: Verify Terraform version
+        run: terraform --version
+
+      - name: Terraform apply
+        uses: nick-fields/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 60
+          retry_wait_seconds: 5
+          command: |
+            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
+              cd "${{ matrix.arrays.terraform_dir }}"
+            else
+              cd terraform/eks/addon/gpu
+            fi
+            
+            terraform init
+            if terraform apply --auto-approve \
+              -var="test_dir=${{ matrix.arrays.test_dir }}"\
+              -var="beta=true" \
+              -var="addon_name=amazon-cloudwatch-observability" \
+              -var="addon_version=v1.6.0-eksbuild.1" \
+              -var="k8s_version=1.29" ; then
+              echo "Terraform apply successful."
+            
+              # Capture the output
+              echo "Getting EKS cluster name"
+              EKS_CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
+              echo "Cluster name is ${EKS_CLUSTER_NAME}"
+              kubectl get pods -A
+              kubectl apply -f ./gpuBurner.yaml
+              kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.15.0/deployments/static/nvidia-device-plugin.yml
+              kubectl patch amazoncloudwatchagents -n amazon-cloudwatch cloudwatch-agent --type='json' -p='[{"op": "replace", "path": "/spec/image", "value": ${{ secrets.AWS_ECR_PRIVATE_REGISTRY }}/${{ env.ECR_INTEGRATION_TEST_REPO }}:${{ github.sha }}}]'
+              #sleep 3 minutes to make sure all metrics are begin generated
+              sleep 180 
+              if go test ${{ matrix.arrays.test_dir }} -eksClusterName ${EKS_CLUSTER_NAME} -computeType=EKS -v -eksDeploymentStrategy=DAEMON -eksGpuType=nvidia; then
+                echo "Tests passed"
+              else
+                echo "Tests failed"
+                exit 1
+              fi
+            else
+              terraform destroy -var="beta=${{ github.event.inputs.run_in_beta }}" -auto-approve && exit 1
+            fi
+
+      - name: Terraform destroy
+        if: ${{ cancelled() || failure() }}
+        uses: nick-fields/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 8
+          retry_wait_seconds: 5
+          command: cd terraform/eks/addon/gpu && terraform destroy --auto-approve
+
 
   EKSIntegrationTest:
     name: 'EKSIntegrationTest'
@@ -1020,85 +1099,6 @@ jobs:
               cd terraform/eks/deployment
             fi
             terraform destroy --auto-approve
-  GPUE2E:
-    name: "GPUE2E"
-    needs: [ BuildAndUpload, BuildAndUploadPackages, GenerateTestMatrix ]
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        arrays: ${{ fromJson(needs.GenerateTestMatrix.outputs.eks_addon_matrix) }}
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
-          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-          aws-region: us-west-2
-          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }}
-
-
-      - name: Verify Terraform version
-        run: terraform --version
-
-      - name: Terraform apply
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 3
-          timeout_minutes: 60
-          retry_wait_seconds: 5
-          command: |
-            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
-              cd "${{ matrix.arrays.terraform_dir }}"
-            else
-              cd terraform/eks/addon/gpu
-            fi
-            
-            terraform init
-            if terraform apply --auto-approve \
-              -var="test_dir=${{ matrix.arrays.test_dir }}"\
-              -var="beta=true" \
-              -var="addon_name=amazon-cloudwatch-observability" \
-              -var="addon_version=v1.6.0-eksbuild.1" \
-              -var="k8s_version=1.29" ; then
-              echo "Terraform apply successful."
-            
-              # Capture the output
-              echo "Getting EKS cluster name"
-              EKS_CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
-              echo "Cluster name is ${EKS_CLUSTER_NAME}"
-              kubectl get pods -A
-              kubectl apply -f ./gpuBurner.yaml
-              kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.15.0/deployments/static/nvidia-device-plugin.yml
-              kubectl patch amazoncloudwatchagents -n amazon-cloudwatch cloudwatch-agent --type='json' -p='[{"op": "replace", "path": "/spec/image", "value": ${{ secrets.AWS_ECR_PRIVATE_REGISTRY }}/${{ env.ECR_INTEGRATION_TEST_REPO }}:${{ github.sha }}}]'
-              #sleep 3 minutes to make sure all metrics are begin generated
-              sleep 180 
-              if go test ${{ matrix.arrays.test_dir }} -eksClusterName ${EKS_CLUSTER_NAME} -computeType=EKS -v -eksDeploymentStrategy=DAEMON -eksGpuType=nvidia; then
-                echo "Tests passed"
-              else
-                echo "Tests failed"
-                exit 1
-              fi
-            else
-              terraform destroy -var="beta=${{ github.event.inputs.run_in_beta }}" -auto-approve && exit 1
-            fi
-
-      - name: Terraform destroy
-        if: ${{ cancelled() || failure() }}
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 3
-          timeout_minutes: 8
-          retry_wait_seconds: 5
-          command: cd terraform/eks/addon/gpu && terraform destroy --auto-approve
-
 
   PerformanceTrackingTest:
     name: "PerformanceTrackingTest"
