updated the yml

diff --git a/.github/workflows/workflowforagent.yml b/.github/workflows/workflowforagent.yml
--- a/.github/workflows/workflowforagent.yml
+++ b/.github/workflows/workflowforagent.yml
@@ -45,36 +45,42 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
-      - name: go mod build
-        run: |
-        
-          time aws s3 cp s3://cloudwatch-agent-integration-bucket/vendorTest/vendor.zip ./vendor.zip
-          time unzip vendor.zip
-#      - name: go mod optimization
+#      - name: go mod build
 #        run: |
-#          if aws s3 ls "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"; then
-#            cd packaging/uniformBuild
-#            time aws s3 cp "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip" ./vendor.zip
-#            time unzip vendor.zip
-#            rm -r vendor.zip
-#            set +e
-#            time (go build -mod=vendor .)
-#            build_exit_status=$?
-#            echo  "build status code:$build_exit_status"
-#            if [ $build_exit_status -ne 0 ]; then   #if package is updated we are able to handle with is this functionality.
-#              echo "Error detected while running 'go build -mod=vendor .'"
-#              go mod tidy
-#              go mod vendor
-#              zip -r vendor.zip vendor
-#              aws s3 cp vendor.zip "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"
-#              rm -f vendor.zip
-#            else
-#              echo "Build successful"
-#            fi
-#          else
-#            time go mod vendor
-#            zip -r vendor.zip vendor
-#            aws s3 cp vendor.zip "s3://cloudwatch-agent-integration-bucket/bhanu/vendor.zip"
-#            echo "vendor zip added to the bucket"
-#          fi
-#          set -e
+#          time aws s3 cp s3://cloudwatch-agent-integration-bucket/vendorTest/vendor.zip ./vendor.zip
+#          time unzip vendor.zip
+      - name: go mod optimization
+        run: |
+          if aws s3 ls "s3://cloudwatch-agent-integration-bucket/vendorTest/vendor.zip"; then
+            time aws s3 cp "s3://cloudwatch-agent-integration-bucket/vendorTest/vendor.zip" ./vendor.zip
+            time unzip vendor.zip
+            rm -r vendor.zip
+            set +e
+            cd cmd/amazon-cloudwatch-agent
+            time (go build -mod=vendor .)
+            build_exit_status=$?
+            echo  "build status code:$build_exit_status"
+            if [ $build_exit_status -ne 0 ]; then   #if package is updated we are able to handle with is this functionality.
+              echo "Error detected while running 'go build -mod=vendor .'"
+              cd -
+              go mod tidy
+              go mod vendor
+              cd cmd/amazon-cloudwatch-agent
+              go build -mod=vendor .
+              cd -
+              zip -r vendor.zip vendor
+              aws s3 cp vendor.zip "s3://cloudwatch-agent-integration-bucket/vendorTest/vendor.zip"
+              rm -f vendor.zip
+            else
+              echo "Build successful"
+            fi
+          else
+            time go mod vendor
+            cd cmd/amazon-cloudwatch-agent
+            go build -mod=vendor .
+            cd -
+            zip -r vendor.zip vendor
+            aws s3 cp vendor.zip "s3://cloudwatch-agent-integration-bucket/vendorTest/vendor.zip"
+            echo "vendor zip added to the bucket"
+          fi
+          set -e
